name: fcoin
version: git
summary: A fullnode Bitcoin implementation for miners, wallets, and exchanges
description: |
  Folmcoin is an alternative implementation of the folm protocol, written in
  node.js.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict

apps:
  fcoin:
    command: fcoin
    plugs: [network, network-bind]

parts:
  fcoin:
    source: .
    plugin: nodejs
    build-packages: [python, gcc]
    node-engine: 7.9.0